/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linecounter;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Gishan-mac
 */
public class LineCounterAllMethods extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    String filename;
    static JFileChooser jfc;

    public LineCounterAllMethods() {
        initComponents();
    }

    void func() throws IOException {
        filename = getPath();
        pathTextField.setText(filename);
        dataTextArea.setText("");
        dataTextArea.setText(LineCounterMethods.charLineCountWithoutComments1(filename));
        locnumLabel.setText(LineCounterMethods.lineCount() + "");

        nofnumLabel.setText(LineCounterMethods.noOfFunctions(filename) + "");
        novnumLabel.setText(LineCounterMethods.noOfVariables(filename) + "");
        nocnumLabel.setText(LineCounterMethods.commentCount() + "");
    }

    String getPath() {
        JFileChooser jfchooser = new JFileChooser();
        jfchooser.setCurrentDirectory(new File("."));
        jfchooser.setDialogTitle("choosertitle");
        jfchooser.setFileFilter(new FileNameExtensionFilter("C/C++/Header", "c", "cpp", ".h"));
        jfchooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfchooser.setAcceptAllFileFilterUsed(false);
        return (jfchooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) ? jfchooser.getSelectedFile().getPath() : null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        fileLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTextArea = new javax.swing.JTextArea();
        locLabel = new javax.swing.JLabel();
        locnumLabel = new javax.swing.JLabel();
        noOfCommentsLabel = new javax.swing.JLabel();
        nocnumLabel = new javax.swing.JLabel();
        noOfFunctionsLabel = new javax.swing.JLabel();
        nofnumLabel = new javax.swing.JLabel();
        noOfVariablesLabel = new javax.swing.JLabel();
        novnumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Line Counter");

        fileLabel.setText("C File :");

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        dataTextArea.setColumns(20);
        dataTextArea.setRows(5);
        jScrollPane1.setViewportView(dataTextArea);

        locLabel.setText("LOC :");

        noOfCommentsLabel.setText("No of comment lines :");

        noOfFunctionsLabel.setText("No of functions :");

        noOfVariablesLabel.setText("No of variables :");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                        .addComponent(fileLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(browseButton))
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                        .addComponent(locLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(nocnumLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(nofnumLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(novnumLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(locnumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(noOfCommentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(noOfFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(noOfVariablesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(browseButton))
                        .addGap(7, 7, 7)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(locnumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(locLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nocnumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noOfCommentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nofnumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noOfFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(novnumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noOfVariablesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // TODO add your handling code here:
            func();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton browseButton;
    private javax.swing.JTextArea dataTextArea;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locLabel;
    private javax.swing.JLabel locnumLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel noOfCommentsLabel;
    private javax.swing.JLabel noOfFunctionsLabel;
    private javax.swing.JLabel noOfVariablesLabel;
    private javax.swing.JLabel nocnumLabel;
    private javax.swing.JLabel nofnumLabel;
    private javax.swing.JLabel novnumLabel;
    private javax.swing.JTextField pathTextField;
    // End of variables declaration                   
}

class LineCounterMethods {

    static int linecount = 0, sourcelinecount, commentlinecount1 = 0;
    static String line, comments, commentsend;

    public static String lineCountWithComments(String filename) throws FileNotFoundException, IOException {
        FileReader fr = new FileReader(filename);
        BufferedReader br = new BufferedReader(fr);
        StringBuilder sb = new StringBuilder();
        line = br.readLine();
        linecount = 0;
        while (line != null) {
            linecount++;
            sb.append(linecount + "\t" + line);
            sb.append(System.lineSeparator());
            line = br.readLine();
        }
        br.close();
        fr.close();
        return sb.toString();
    }

    public static int lineCount() {
        return linecount;
    }

    public static String charLineCountWithoutComments1(String filename) throws FileNotFoundException, IOException {
        FileReader fr = new FileReader(filename);
        BufferedReader br = new BufferedReader(fr);
        StringBuilder sb = new StringBuilder();
        line = br.readLine();
        linecount = 0;
        w1:
        while (line != null) {
            while (line.length() == 0) {
                sb.append("\t" + line);
                sb.append(System.lineSeparator());
                line = br.readLine();
            }
            char currentline[] = line.toCharArray();
            boolean a = true, d = true, e = true, f = true;
            f1:
            for (int i = 0; i < currentline.length - 1; i++) {
                String s = String.valueOf(currentline[i]) + String.valueOf(currentline[i + 1]);
                String ss = String.valueOf(currentline[i]);
                if (!s.equals("//")) {
                    a = false;
                } else if (!s.equals("/*")) {
                    d = false;
                } else if (!ss.equals(" ")) {
                    e = false;
                }
//                System.out.println(s + "   " + (s.equals("//")));
                if (s.equals("//") && a && e) {
                    commentlinecount1++;
                    sb.append("\t" + line);
                    sb.append(System.lineSeparator());
                    line = br.readLine();
                    continue w1;
                } else if (s.equals("/*") && d) {
                    commentlinecount1++;
                    boolean b = true;
                    for (int j = i; j < currentline.length - 1; j++) {
                        String star = String.valueOf(currentline[j]) + String.valueOf(currentline[j + 1]);
                        if (star.equals("*/")) {
                            sb.append("\t" + line);
                            sb.append(System.lineSeparator());
                            line = br.readLine();
                            break f1;
//                             }  else {
//                                linecount++;
//                                sb.append(linecount + "\t" + line);
//                                sb.append(System.lineSeparator());
//                          
                            // b = false;
//                        commentsend = (line != null && line.length() >= 2) ? line.substring(line.length() - 2, line.length()) : line;
                        }
                    }
                    while ((!line.endsWith("*/")) && b) {
                        commentlinecount1++;
                        sb.append("\t" + line);
                        sb.append(System.lineSeparator());
                        line = br.readLine();
                    }
                    if (line.endsWith("*/")) {
                        sb.append("\t" + line);
                        sb.append(System.lineSeparator());
                        line = br.readLine();
//                        commentsend = (line != null && line.length() >= 2) ? line.substring(line.length() - 2, line.length()) : line;
                    }
                    continue w1;
                }
            }
            linecount++;
            sb.append(linecount + "\t" + line);
            sb.append(System.lineSeparator());
            line = br.readLine();
        }
        br.close();
        fr.close();
        return sb.toString();
    }

    public static int commentCount() {
        return commentlinecount1;
    }

    public static int noOfFunctions(String filename) throws FileNotFoundException, IOException {
        FileReader fr = new FileReader(filename);
        BufferedReader br = new BufferedReader(fr);
        line = br.readLine();
        int nooffunctions = 0;
        while (line != null) {
            if ((line.startsWith("void") || line.startsWith("char") || line.startsWith("int") || line.startsWith("float") || line.startsWith("short") || line.startsWith("long")) && (line.endsWith(") {") || line.endsWith("){"))) {
                nooffunctions++;
                System.out.println("Functions - " + line);
            }
            line = br.readLine();
        }
        br.close();
        fr.close();
        return nooffunctions;
    }

    public static int noOfVariables(String filename) throws FileNotFoundException, IOException {
        FileReader fr = new FileReader(filename);
        BufferedReader br = new BufferedReader(fr);
        line = br.readLine();
        int noofvariables = 0;
        while (line != null) {
            if ((line.startsWith("void") || line.startsWith("char") || line.startsWith("int") || line.startsWith("float") || line.startsWith("short") || line.startsWith("long")) && !line.endsWith(");") && line.endsWith(";")) {
                char currentline[] = line.toCharArray();
                for (int i = 0; i < currentline.length; i++) {
                    if (currentline[i] == ',' || currentline[i] == ';') {
                        noofvariables++;
                    }
                }
                System.out.println("Variables - " + line);
            }
            line = br.readLine();
        }
        br.close();
        fr.close();
        return noofvariables;
    }
}
